version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins-project:latest
    container_name: Jenkins
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
